# Generated by Django 4.2.23 on 2025-07-09 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingsession',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle'),
        ),
    ]
