# Generated by Django 4.2.23 on 2025-07-09 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('session', '0002_parkingsession_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.CharField(max_length=255)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('method', models.CharField(choices=[('heuristic', 'Heurístico'), ('rule_based', 'Reglas'), ('ml', 'Machine Learning'), ('ai', 'IA Avanzada'), ('manual', 'Manual')], default='heuristic', max_length=20)),
                ('score', models.FloatField(default=0.0, help_text='Nivel de confianza en la recomendación')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_parking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_for', to='parking.parking')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_suggestion', to='session.parkingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sugerencia',
                'verbose_name_plural': 'Sugerencias',
                'ordering': ['-created_at'],
            },
        ),
    ]
