# Generated by Django 4.2.23 on 2025-07-09 17:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='La patente debe tener un formato como AB123 o ABC-123', regex='^[A-Z]{2,3}-?\\d{2,3}$')])),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2026)])),
                ('vehicle_type', models.CharField(choices=[('car', 'Automóvil'), ('motorcycle', 'Motocicleta'), ('suv', 'SUV'), ('truck', 'Camión'), ('van', 'Furgoneta'), ('electric', 'Eléctrico'), ('other', 'Otro')], default='car', max_length=20)),
                ('engine_type', models.CharField(choices=[('gasoline', 'Gasolina'), ('diesel', 'Diésel'), ('electric', 'Eléctrico'), ('hybrid', 'Híbrido'), ('other', 'Otro')], default='gasoline', max_length=20)),
                ('color', models.CharField(choices=[('white', 'Blanco'), ('black', 'Negro'), ('gray', 'Gris'), ('blue', 'Azul'), ('red', 'Rojo'), ('silver', 'Plateado'), ('green', 'Verde'), ('yellow', 'Amarillo'), ('other', 'Otro')], default='white', max_length=20)),
                ('mileage', models.PositiveIntegerField(default=0, help_text='Kilometraje actual en km')),
                ('insurance_expiration', models.DateField(blank=True, null=True)),
                ('technical_revision_date', models.DateField(blank=True, null=True)),
                ('is_electric', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicle_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['-created_at'],
            },
        ),
    ]
