# Generated by Django 4.2.23 on 2025-07-04 18:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('center', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('main_access_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('zone_type', models.CharField(choices=[('residential', 'Residencial'), ('commercial', 'Comercial'), ('mall', 'Centro Comercial'), ('university', 'Universidad'), ('airport', 'Aeropuerto')], default='commercial', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='parking.city')),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('type', models.CharField(max_length=50)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pois', to='locations.locationzone')),
            ],
        ),
    ]
