# Generated by Django 4.2.23 on 2025-07-07 17:08

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Route Request',
                'verbose_name_plural': 'Route Requests',
            },
        ),
        migrations.CreateModel(
            name='RecommendedZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_zones', to='directions.routerequest')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='locations.locationzone')),
            ],
            options={
                'verbose_name': 'Recommended Zone',
                'verbose_name_plural': 'Recommended Zones',
            },
        ),
    ]
